# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\trimaudio.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_audio_ofset(object):
    def setupUi(self, audio_ofset):
        audio_ofset.setObjectName("audio_ofset")
        audio_ofset.resize(510, 208)
        audio_ofset.setMinimumSize(QtCore.QSize(510, 208))
        audio_ofset.setMaximumSize(QtCore.QSize(510, 208))
        audio_ofset.setStyleSheet("QWidget {\n"
"    background-color: #2a2a2a;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(audio_ofset)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.audio_spectrum_frame = QtWidgets.QFrame(audio_ofset)
        self.audio_spectrum_frame.setStyleSheet("QFrame {\n"
"    border-radius: 4px;\n"
"    background-color:#3b3b3b;\n"
"}")
        self.audio_spectrum_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.audio_spectrum_frame.setObjectName("audio_spectrum_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.audio_spectrum_frame)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.audio_spectrum_view = QtWidgets.QFrame(self.audio_spectrum_frame)
        self.audio_spectrum_view.setStyleSheet("QFrame {\n"
"    border : 1px solid #4C6C3F;\n"
"    border-radius: 8px;\n"
"    background-color:#323232;\n"
"}")
        self.audio_spectrum_view.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.audio_spectrum_view.setObjectName("audio_spectrum_view")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.audio_spectrum_view)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Track_root_path_horizontalLayout = QtWidgets.QHBoxLayout()
        self.Track_root_path_horizontalLayout.setObjectName("Track_root_path_horizontalLayout")
        self.label_root_path = QtWidgets.QLabel(self.audio_spectrum_view)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_root_path.setFont(font)
        self.label_root_path.setStyleSheet(" QLabel {\n"
"    color: rgb(150, 150, 150);\n"
"    border : none;\n"
"    border-radius: none;\n"
"    background-color:none;\n"
"}")
        self.label_root_path.setObjectName("label_root_path")
        self.Track_root_path_horizontalLayout.addWidget(self.label_root_path)
        self.lineEdit_path = QtWidgets.QLineEdit(self.audio_spectrum_view)
        self.lineEdit_path.setMinimumSize(QtCore.QSize(282, 25))
        self.lineEdit_path.setMaximumSize(QtCore.QSize(282, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_path.setFont(font)
        self.lineEdit_path.setStyleSheet("QLineEdit {\n"
"    color: #548f54;\n"
"    border: 1px solid #215740;\n"
"    border-radius: 4px;\n"
"    padding: 0 8px;\n"
"    background: #212121;\n"
"    selection-background-color: #212121;\n"
"}")
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.Track_root_path_horizontalLayout.addWidget(self.lineEdit_path)
        self.toolButton_select_track = QtWidgets.QToolButton(self.audio_spectrum_view)
        self.toolButton_select_track.setStyleSheet("QToolButton { /* all types of tool button */\n"
"    color:#4A702B;\n"
"    border: 1px solid #215740;\n"
"    border-radius: 6px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #151616, stop: 1 #1C1D1C);\n"
"    min-width: 25px;\n"
"    min-height: 23px;\n"
"\n"
"}\n"
"\n"
"QToolButton[popupMode=\"1\"] { /* only for MenuButtonPopup */\n"
"    padding-right: 20px; /* make way for the popup button */\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #1C1D1C, stop: 1 #151616);\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    color: #151616;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #4A702B, stop: 1 #215740);    \n"
"}\n"
"\n"
"/* the subcontrols below are used only in the MenuButtonPopup mode */\n"
"QToolButton::menu-button {\n"
"    border: 1px solid #1C1D1C;\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"    /* 16px width + 4px for border = 20px allocated above */\n"
"    width: 16px;\n"
"}\n"
"\n"
"QToolButton::menu-arrow:open {\n"
"    top: 1px; left: 1px; /* shift it a bit */\n"
"}")
        self.toolButton_select_track.setObjectName("toolButton_select_track")
        self.Track_root_path_horizontalLayout.addWidget(self.toolButton_select_track)
        self.pushButton_track_pathReset = QtWidgets.QPushButton(self.audio_spectrum_view)
        self.pushButton_track_pathReset.setMinimumSize(QtCore.QSize(62, 27))
        self.pushButton_track_pathReset.setMaximumSize(QtCore.QSize(60, 25))
        self.pushButton_track_pathReset.setStyleSheet("QPushButton {\n"
"    color:#4A702B;\n"
"    border: 1px solid #215740;\n"
"    border-radius: 4px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #151616, stop: 1 #1C1D1C);\n"
"    min-width: 60px;\n"
"    min-height: 25px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #151616;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #4A702B, stop: 1 #215740);    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #4A702B;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #1C1D1C, stop: 1 #151616);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}")
        self.pushButton_track_pathReset.setObjectName("pushButton_track_pathReset")
        self.Track_root_path_horizontalLayout.addWidget(self.pushButton_track_pathReset)
        self.verticalLayout_3.addLayout(self.Track_root_path_horizontalLayout)
        self.Track_horizontalLayout = QtWidgets.QHBoxLayout()
        self.Track_horizontalLayout.setObjectName("Track_horizontalLayout")
        self.label_TrackName = QtWidgets.QLabel(self.audio_spectrum_view)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_TrackName.setFont(font)
        self.label_TrackName.setStyleSheet(" QLabel {\n"
"    color: rgb(150, 150, 150);\n"
"    border : none;\n"
"    border-radius: none;\n"
"    background-color:none;\n"
"}")
        self.label_TrackName.setObjectName("label_TrackName")
        self.Track_horizontalLayout.addWidget(self.label_TrackName)
        self.lineEdit_trackName = QtWidgets.QLineEdit(self.audio_spectrum_view)
        self.lineEdit_trackName.setMinimumSize(QtCore.QSize(317, 25))
        self.lineEdit_trackName.setMaximumSize(QtCore.QSize(317, 25))
        self.lineEdit_trackName.setStyleSheet("QLineEdit {\n"
"    color: #548f54;\n"
"    border: 1px solid #215740;\n"
"    border-radius: 4px;\n"
"    padding: 0 8px;\n"
"    background: #212121;\n"
"    selection-background-color: #212121;\n"
"}")
        self.lineEdit_trackName.setObjectName("lineEdit_trackName")
        self.Track_horizontalLayout.addWidget(self.lineEdit_trackName)
        self.pushButton_trackNameReset = QtWidgets.QPushButton(self.audio_spectrum_view)
        self.pushButton_trackNameReset.setMinimumSize(QtCore.QSize(62, 27))
        self.pushButton_trackNameReset.setMaximumSize(QtCore.QSize(60, 25))
        self.pushButton_trackNameReset.setStyleSheet("QPushButton {\n"
"    color:#4A702B;\n"
"    border: 1px solid #215740;\n"
"    border-radius: 4px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #151616, stop: 1 #1C1D1C);\n"
"    min-width: 60px;\n"
"    min-height: 25px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #151616;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #4A702B, stop: 1 #215740);    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #4A702B;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #1C1D1C, stop: 1 #151616);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}")
        self.pushButton_trackNameReset.setObjectName("pushButton_trackNameReset")
        self.Track_horizontalLayout.addWidget(self.pushButton_trackNameReset)
        self.verticalLayout_3.addLayout(self.Track_horizontalLayout)
        self.offset_horizontalLayout = QtWidgets.QHBoxLayout()
        self.offset_horizontalLayout.setObjectName("offset_horizontalLayout")
        self.label_offset = QtWidgets.QLabel(self.audio_spectrum_view)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_offset.setFont(font)
        self.label_offset.setStyleSheet(" QLabel {\n"
"    color: rgb(150, 150, 150);\n"
"    border : none;\n"
"    border-radius: none;\n"
"    background-color:none;\n"
"}")
        self.label_offset.setObjectName("label_offset")
        self.offset_horizontalLayout.addWidget(self.label_offset)
        self.pushButton_prevFrame = QtWidgets.QPushButton(self.audio_spectrum_view)
        self.pushButton_prevFrame.setMinimumSize(QtCore.QSize(27, 25))
        self.pushButton_prevFrame.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_prevFrame.setFont(font)
        self.pushButton_prevFrame.setStyleSheet("QPushButton {\n"
"    color:#4A702B;\n"
"    border: 1px solid #215740;\n"
"    border-radius: 4px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #151616, stop: 1 #1C1D1C);\n"
"    min-width: 25px;\n"
"    min-height: 23px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #151616;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #4A702B, stop: 1 #215740);    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #4A702B;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #1C1D1C, stop: 1 #151616);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}")
        self.pushButton_prevFrame.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/prev.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_prevFrame.setIcon(icon)
        self.pushButton_prevFrame.setObjectName("pushButton_prevFrame")
        self.offset_horizontalLayout.addWidget(self.pushButton_prevFrame)
        self.lineEdit_offset_frame = QtWidgets.QLineEdit(self.audio_spectrum_view)
        self.lineEdit_offset_frame.setMinimumSize(QtCore.QSize(124, 25))
        self.lineEdit_offset_frame.setMaximumSize(QtCore.QSize(124, 25))
        self.lineEdit_offset_frame.setStyleSheet("QLineEdit {\n"
"    color: #548f54;\n"
"    border: 1px solid #215740;\n"
"    border-radius: 4px;\n"
"    padding: 0 8px;\n"
"    background: #212121;\n"
"    selection-background-color: #212121;\n"
"}")
        self.lineEdit_offset_frame.setObjectName("lineEdit_offset_frame")
        self.offset_horizontalLayout.addWidget(self.lineEdit_offset_frame)
        self.lineEdit_tail_offset_frame = QtWidgets.QLineEdit(self.audio_spectrum_view)
        self.lineEdit_tail_offset_frame.setMinimumSize(QtCore.QSize(124, 25))
        self.lineEdit_tail_offset_frame.setMaximumSize(QtCore.QSize(124, 25))
        self.lineEdit_tail_offset_frame.setStyleSheet("QLineEdit {\n"
"    color: #548f54;\n"
"    border: 1px solid #215740;\n"
"    border-radius: 4px;\n"
"    padding: 0 8px;\n"
"    background: #212121;\n"
"    selection-background-color: #212121;\n"
"}")
        self.lineEdit_tail_offset_frame.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_tail_offset_frame.setObjectName("lineEdit_tail_offset_frame")
        self.offset_horizontalLayout.addWidget(self.lineEdit_tail_offset_frame)
        self.PushButton_nextFrame = QtWidgets.QPushButton(self.audio_spectrum_view)
        self.PushButton_nextFrame.setMinimumSize(QtCore.QSize(27, 25))
        self.PushButton_nextFrame.setMaximumSize(QtCore.QSize(25, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.PushButton_nextFrame.setFont(font)
        self.PushButton_nextFrame.setStyleSheet("QPushButton {\n"
"    color:#4A702B;\n"
"    border: 1px solid #215740;\n"
"    border-radius: 4px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #151616, stop: 1 #1C1D1C);\n"
"    min-width: 25px;\n"
"    min-height: 23px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #151616;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #4A702B, stop: 1 #215740);    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #4A702B;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #1C1D1C, stop: 1 #151616);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}")
        self.PushButton_nextFrame.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PushButton_nextFrame.setIcon(icon1)
        self.PushButton_nextFrame.setObjectName("PushButton_nextFrame")
        self.offset_horizontalLayout.addWidget(self.PushButton_nextFrame)
        self.pushButton_frameReset = QtWidgets.QPushButton(self.audio_spectrum_view)
        self.pushButton_frameReset.setMinimumSize(QtCore.QSize(62, 27))
        self.pushButton_frameReset.setMaximumSize(QtCore.QSize(60, 25))
        self.pushButton_frameReset.setStyleSheet("QPushButton {\n"
"    color:#4A702B;\n"
"    border: 1px solid #215740;\n"
"    border-radius: 4px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #151616, stop: 1 #1C1D1C);\n"
"    min-width: 60px;\n"
"    min-height: 25px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #151616;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #4A702B, stop: 1 #215740);    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #4A702B;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #1C1D1C, stop: 1 #151616);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}")
        self.pushButton_frameReset.setObjectName("pushButton_frameReset")
        self.offset_horizontalLayout.addWidget(self.pushButton_frameReset)
        self.verticalLayout_3.addLayout(self.offset_horizontalLayout)
        self.audio_spectrum_horizontalLayout = QtWidgets.QHBoxLayout()
        self.audio_spectrum_horizontalLayout.setObjectName("audio_spectrum_horizontalLayout")
        self.frame_Controls = QtWidgets.QFrame(self.audio_spectrum_view)
        self.frame_Controls.setMinimumSize(QtCore.QSize(332, 80))
        self.frame_Controls.setMaximumSize(QtCore.QSize(332, 80))
        self.frame_Controls.setStyleSheet("QFrame {\n"
"    border: 1px solid #215740;\n"
"    border-radius: 4px;\n"
"    background-color:none;\n"
"}")
        self.frame_Controls.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_Controls.setObjectName("frame_Controls")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_Controls)
        self.verticalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.playSlider = QtWidgets.QSlider(self.frame_Controls)
        self.playSlider.setMinimumSize(QtCore.QSize(0, 4))
        self.playSlider.setMaximumSize(QtCore.QSize(16777215, 4))
        self.playSlider.setStyleSheet("QSlider {\n"
"    background-color: rgb(0, 85, 0, 0);\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #B1B1B1, stop:1 #c4c4c4);\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #4A702B, stop: 1 #215740);    \n"
"    border: 1px solid #5c5c5c;\n"
"    width: 1px;\n"
"    margin: -5px 0;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background:qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #4A702B, stop: 1 #215740);\n"
"}")
        self.playSlider.setOrientation(QtCore.Qt.Horizontal)
        self.playSlider.setObjectName("playSlider")
        self.verticalLayout_4.addWidget(self.playSlider)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_play_time = QtWidgets.QLabel(self.frame_Controls)
        self.label_play_time.setStyleSheet(" QLabel {\n"
"    color: rgb(150, 150, 150);\n"
"    border : none;\n"
"    border-radius: none;\n"
"    background-color:none;\n"
"}")
        self.label_play_time.setText("")
        self.label_play_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_play_time.setObjectName("label_play_time")
        self.horizontalLayout_2.addWidget(self.label_play_time)
        self.line = QtWidgets.QFrame(self.frame_Controls)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.label_play_remain = QtWidgets.QLabel(self.frame_Controls)
        self.label_play_remain.setStyleSheet(" QLabel {\n"
"    color: rgb(150, 150, 150);\n"
"    border : none;\n"
"    border-radius: none;\n"
"    background-color:none;\n"
"}")
        self.label_play_remain.setText("")
        self.label_play_remain.setAlignment(QtCore.Qt.AlignCenter)
        self.label_play_remain.setObjectName("label_play_remain")
        self.horizontalLayout_2.addWidget(self.label_play_remain)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(3, 0, 3, 3)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_back_seeek = QtWidgets.QPushButton(self.frame_Controls)
        self.pushButton_back_seeek.setMinimumSize(QtCore.QSize(27, 25))
        self.pushButton_back_seeek.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_back_seeek.setStyleSheet("QPushButton {\n"
"    color:#4A702B;\n"
"    border: 1px solid #215740;\n"
"    border-radius: 4px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #151616, stop: 1 #1C1D1C);\n"
"    min-width: 25px;\n"
"    min-height: 23px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #151616;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #4A702B, stop: 1 #215740);    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #4A702B;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #1C1D1C, stop: 1 #151616);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}")
        self.pushButton_back_seeek.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/backword.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_back_seeek.setIcon(icon2)
        self.pushButton_back_seeek.setObjectName("pushButton_back_seeek")
        self.horizontalLayout.addWidget(self.pushButton_back_seeek)
        self.pushButton_play = QtWidgets.QPushButton(self.frame_Controls)
        self.pushButton_play.setMinimumSize(QtCore.QSize(27, 25))
        self.pushButton_play.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_play.setStyleSheet("QPushButton {\n"
"    color:#4A702B;\n"
"    border: 1px solid #215740;\n"
"    border-radius: 4px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #151616, stop: 1 #1C1D1C);\n"
"    min-width: 25px;\n"
"    min-height: 23px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #151616;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #4A702B, stop: 1 #215740);    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #4A702B;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #1C1D1C, stop: 1 #151616);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}")
        self.pushButton_play.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_play.setIcon(icon3)
        self.pushButton_play.setObjectName("pushButton_play")
        self.horizontalLayout.addWidget(self.pushButton_play)
        self.pushButton_seek = QtWidgets.QPushButton(self.frame_Controls)
        self.pushButton_seek.setMinimumSize(QtCore.QSize(27, 25))
        self.pushButton_seek.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_seek.setStyleSheet("QPushButton {\n"
"    color:#4A702B;\n"
"    border: 1px solid #215740;\n"
"    border-radius: 4px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #151616, stop: 1 #1C1D1C);\n"
"    min-width: 25px;\n"
"    min-height: 23px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #151616;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #4A702B, stop: 1 #215740);    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #4A702B;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #1C1D1C, stop: 1 #151616);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}")
        self.pushButton_seek.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_seek.setIcon(icon4)
        self.pushButton_seek.setObjectName("pushButton_seek")
        self.horizontalLayout.addWidget(self.pushButton_seek)
        self.pushButton_repeat = QtWidgets.QPushButton(self.frame_Controls)
        self.pushButton_repeat.setMinimumSize(QtCore.QSize(27, 25))
        self.pushButton_repeat.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_repeat.setStyleSheet("QPushButton {\n"
"    color:#4A702B;\n"
"    border: 1px solid #215740;\n"
"    border-radius: 4px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #151616, stop: 1 #1C1D1C);\n"
"    min-width: 25px;\n"
"    min-height: 23px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #151616;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #4A702B, stop: 1 #215740);    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #4A702B;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #1C1D1C, stop: 1 #151616);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}")
        self.pushButton_repeat.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/replay.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_repeat.setIcon(icon5)
        self.pushButton_repeat.setObjectName("pushButton_repeat")
        self.horizontalLayout.addWidget(self.pushButton_repeat)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.audio_spectrum_horizontalLayout.addWidget(self.frame_Controls)
        self.pushButton = QtWidgets.QPushButton(self.audio_spectrum_view)
        self.pushButton.setMinimumSize(QtCore.QSize(120, 80))
        self.pushButton.setMaximumSize(QtCore.QSize(150, 80))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    color:#4A702B;\n"
"    border: 1px solid #215740;\n"
"    border-radius: 4px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #151616, stop: 1 #1C1D1C);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #151616;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #4A702B, stop: 1 #215740);    \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #4A702B;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #1C1D1C, stop: 1 #151616);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.audio_spectrum_horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_3.addLayout(self.audio_spectrum_horizontalLayout)
        self.verticalLayout.addWidget(self.audio_spectrum_view)
        self.gridLayout.addWidget(self.audio_spectrum_frame, 1, 0, 1, 1)

        self.retranslateUi(audio_ofset)
        QtCore.QMetaObject.connectSlotsByName(audio_ofset)

    def retranslateUi(self, audio_ofset):
        _translate = QtCore.QCoreApplication.translate
        audio_ofset.setWindowTitle(_translate("audio_ofset", "Audio Offset Exporter"))
        self.label_root_path.setText(_translate("audio_ofset", "Track Root Path"))
        self.toolButton_select_track.setText(_translate("audio_ofset", "..."))
        self.pushButton_track_pathReset.setText(_translate("audio_ofset", "Reset"))
        self.label_TrackName.setText(_translate("audio_ofset", "Track Name"))
        self.pushButton_trackNameReset.setText(_translate("audio_ofset", "Reset"))
        self.label_offset.setText(_translate("audio_ofset", "Offset"))
        self.lineEdit_offset_frame.setPlaceholderText(_translate("audio_ofset", "offset start frame"))
        self.lineEdit_tail_offset_frame.setPlaceholderText(_translate("audio_ofset", "offset tail frame"))
        self.pushButton_frameReset.setText(_translate("audio_ofset", "Reset"))
        self.pushButton.setText(_translate("audio_ofset", "Publish"))
